### PR TITLE
Fix a type in introduction documentation.

### PR DESCRIPTION
**Pull request by stylesen**
I found this while going through the process documentation and wanted to contribute a typo fix :)

### CODE REVIEW

**Comment by phildini** [comment]
I'm sure this is a fine change, but I can't find what the difference is. :(

**Comment by stylesen** [comment]
I fixed a typo in the above change ie., s/fist/first/

**Comment by kenhys** [comment]
Why this PR is not merged yet? > @paulproteus

**Comment by paulproteus** [comment]
Hi @kenhys ! Thanks for asking. The only reason - I had forgotten about it. I appreciate you bringing it to my attention, and I'll merge it now.

Thanks to:
- @phildini for initial review
- @stylesen for proposing the change

**Pull request merged**
