### PR TITLE
Support mailto for RFS template

### PR DESCRIPTION
**Pull request by kenhys**
This PR aims to provide the following features
- Support mailto: link to send RFS via E-mail
- Show more package detail in /sponsor/rfs-howto/[PACKAGE] page
  such as upstream author, url, license and changelog

### CODE REVIEW

**Comment by kenhys** [comment]
I've intended to improve this interface in this PR.

rfstemplate-mailto

**Comment by olasd** [comment]
Oooooh, that approach is really smart. I'll take a closer look later.

**Comment by kenhys** [comment]
ping @olasd, any progress?

**Comment by kenhys** [comment]
ping @paulproteus

**Comment by paulproteus** [comment]
Hi @olasd & @kenhys ,

Thanks for filing it and the initial review. I'll try to take a look on Monday (in two days). If I don't, then it will have to wait until during Debconf.

**Comment by kenhys** [comment]
Note that this PR is assumed #40 is already merged because python-debian 0.1.23 or later is required.
wheezy provides python-debian 0.1.21, jessie provides python-debian 0.1.27.

**Comment by kenhys** [comment]
I've updated PR to emphasize template link to find it easily.

debexpo-emphasize-mailto

**Comment by kenhys** [comment]
prelimitary-category-severity

I supported category and severity partially.

**Comment by kenhys** [comment]
@paulproteus any progress in review process?

**Comment by kenhys** [comment]
ping @paulproteus ?

**Comment by mapreri** [comment]
@kenhys 

So, after so much time, this work has been picked up again.
Baptiste rebased your work here, and re-posted it [on salsa.d.o](https://salsa.debian.org/mentors.debian.net-team/debexpo/merge_requests/80), where I already commented.

Incidentally, privately he also shared plans on also picking up #45

**Comment by kenhys** [comment]
@mapreri 
thank you for sharering a current status.
I'm happy to hear rebooting issue!

**Comment by mapreri** [comment]
Thank you for your original work, and I'm sorry it took so long to actually lead anywhere!

**Comment by mapreri** [comment]
An update: after Baptiste refactored it a bit and added quite a few bits here and there, I merged the thing!

The updated code is already running live on mentors.debian.net, if you wish to try it out :)

Thank you again for starting the work on this!

**Pull request closed without merging**
